# Generated by Django 4.1 on 2023-05-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allIngredientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_ko_name', models.CharField(default='', max_length=1000)),
                ('ingredient_en_name', models.CharField(default='', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'allIngredientList',
            },
        ),
        migrations.CreateModel(
            name='restrictList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict_regulate_type', models.CharField(max_length=10, null=True)),
                ('restrict_name_ko', models.CharField(max_length=200)),
                ('restrict_name_en', models.CharField(max_length=200)),
                ('restrict_country', models.CharField(max_length=10, null=True)),
                ('restrict_limit', models.TextField(null=True)),
            ],
            options={
                'db_table': 'restrictList',
            },
        ),
    ]
