# Generated by Django 4.1 on 2023-05-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allingredientlist',
            name='ingredient_en_name',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='allingredientlist',
            name='ingredient_ko_name',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
