# Generated by Django 4.1 on 2023-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0002_alter_allingredientlist_ingredient_en_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredeintList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_ko_name', models.CharField(max_length=2000)),
                ('ingredient_en_name', models.CharField(max_length=2000)),
                ('restrict_name_ko', models.CharField(max_length=200)),
                ('restrict_name_en', models.CharField(max_length=200)),
                ('restrict_regulate_type', models.CharField(max_length=10, null=True)),
                ('restrict_limit', models.TextField(null=True)),
                ('restrict_country', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'ingredientList',
            },
        ),
    ]
