# Generated by Django 4.1 on 2023-05-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0003_ingredeintlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredeintlist',
            name='restrict_name_en',
        ),
        migrations.RemoveField(
            model_name='ingredeintlist',
            name='restrict_name_ko',
        ),
        migrations.AddField(
            model_name='ingredeintlist',
            name='restrict_type',
            field=models.BooleanField(default=False),
        ),
    ]
