# Generated by Django 4.1 on 2023-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0004_remove_ingredeintlist_restrict_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictlist',
            name='restrict_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
