# Generated by Django 4.1 on 2023-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0005_alter_restrictlist_restrict_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
