# Generated by Django 4.1 on 2023-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0006_imgpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
