# Generated by Django 4.1 on 2023-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrictIng', '0007_alter_imgpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
